services:
  db:
    image: postgres:18-alpine
    container_name: blog_pg18
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pg18_data:/var/lib/postgresql/data
    
  adminer:
    image: adminer:latest
    container_name: blog_adminer
    restart: always
    ports:
      - "8080:8080"

  backend:
    image: blog-backend:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blog_backend
    restart: unless-stopped
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./uploads:/app/uploads
      - ./public:/app/public
      - ./drizzle:/app/drizzle
    depends_on:
      - db

volumes:
  pg18_data:
    name: blog_pg18_data